### ISSUE TITLE
Error while adding dependencies, what should i do?

### ISSUE THREAD

**Issue by shubham-abnave** [shubham0204/Text2Summary-Android#2]
ERROR: Failed to resolve: com.github.shubham0204:Text2Summary-Android:alpha-02
Show in Project Structure dialog
Affected Modules: app

**Comment by shubham0204** [comment]
Considering the issue, I have released a new version alpha-04. and also updated the README with installation instructions. I tried installing the library once again in an Android project ( using the alpha-04 ) and it builds with no errors. Make sure you have added the `maven { url "https://jitpack.io" }` repo in the `allprojects`  block and not `buildscript` block.

**Comment by shubham-abnave** [comment]
Thanks for that superfast reply!!
Now there is no issues while adding dependencies to gradle file.
But now there is other error   **Cannot resolve symbol Text2Summary**    even after complete gradle sync.
As i looked down this library, source files are written in kotlin, and in my application i am using Java, Is it cause of error?
`String text=stringBuilder.toString();
                String  summarized_text = Text2Summary.summarize( text , compressionRate = 0.7 );`

**Comment by shubham0204** [comment]
Although Kotlin uses JVM under the hood, using it in Java files shouldn't cause an error. I have posted a [question on StackOverflow](https://stackoverflow.com/questions/62340066/how-do-i-run-kotlin-libraries-distributed-via-jitpack-in-a-java-file) regarding the same. I am not sure, but you can try enabling Kotlin in your Android project and then try using the library.

**Comment by shubham-abnave** [comment]
Actually i was unable to add Text2Summary in my MainActivity.java , so I just created a new kotlin class and used Text2Summary there and It is running perfectly now.
Thanks for creating this library!!

**Comment by shubham0204** [comment]
This issue has been fixed in the release [alpha-05](https://github.com/shubham0204/Text2Summary-Android/releases/tag/alpha-05).
