### ISSUE TITLE
Not able to find SummaryCallback and summarizeAsync

### ISSUE THREAD

**Issue by HimanshuChahal** [shubham0204/Text2Summary-Android#3]
Hey Shubham,
Thanks for the repo.

I am using the 'alpha-02' version of the library. It is not able to find SummaryCallback and summarizeAsync. Also, Text2Summary is not getting imported into Java Files.

Code Reference:-
```
fun summarizeText(text: String) {
        val callback = object : Text2Summary.SummaryCallback {
            override fun onSummaryProduced(summary: String) {
                // The summary is ready!
            }
        }
        Text2Summary.summarizeAsync(text, 0.7f , callback)
        var summary = Text2Summary.summarize(text, compressionRate = 0.7f)
    }
```

**Comment by shubham0204** [comment]
@HimanshuChahal Refer to this issue ( #2 ) and it was resolved in the version `alpha-05`.

**Comment by HimanshuChahal** [comment]
Thanks for your response @shubham0204.
It's working with the alpha-05 version.
